# Generated by Django
# ============================================================
# EV TRACKING - INITIAL MIGRATION
# Migration: 0001
# ============================================================

import django.db.models.deletion

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    # ========================================================
    # INITIAL MIGRATION
    # ========================================================

    initial = True


    # ========================================================
    # DEPENDENCIES
    # ========================================================

    dependencies = [
        migrations.swappable_dependency(
            settings.AUTH_USER_MODEL
        ),
    ]


    # ========================================================
    # DATABASE OPERATIONS
    # ========================================================

    operations = [

        # ====================================================
        # 1. CHARGING STATION
        # ====================================================

        migrations.CreateModel(
            name='ChargingStation',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),

                (
                    'name',
                    models.CharField(
                        max_length=200
                    )
                ),

                (
                    'latitude',
                    models.FloatField()
                ),

                (
                    'longitude',
                    models.FloatField()
                ),

                (
                    'chargers_available',
                    models.IntegerField(
                        default=4
                    )
                ),

                (
                    'chargers_total',
                    models.IntegerField(
                        default=4
                    )
                ),

                (
                    'charger_type',
                    models.CharField(
                        choices=[
                            (
                                'level1',
                                'Level 1 (120V)'
                            ),
                            (
                                'level2',
                                'Level 2 (240V)'
                            ),
                            (
                                'dcfc',
                                'DC Fast Charging'
                            ),
                        ],
                        default='level2',
                        max_length=20
                    )
                ),

                (
                    'power_capacity',
                    models.FloatField(
                        default=50.0
                    )
                ),

                (
                    'amenities',
                    models.TextField(
                        blank=True
                    )
                ),

                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True
                    )
                ),
            ],

            options={
                'ordering': ['name'],
            },
        ),


        # ====================================================
        # 2. ROUTE
        # ====================================================

        migrations.CreateModel(
            name='Route',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),

                (
                    'origin_lat',
                    models.FloatField()
                ),

                (
                    'origin_lon',
                    models.FloatField()
                ),

                (
                    'destination_lat',
                    models.FloatField()
                ),

                (
                    'destination_lon',
                    models.FloatField()
                ),

                (
                    'distance',
                    models.FloatField()
                ),

                (
                    'estimated_duration',
                    models.IntegerField()
                ),

                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True
                    )
                ),
            ],
        ),


        # ====================================================
        # 3. EV VEHICLE
        # ====================================================

        migrations.CreateModel(
            name='EVVehicle',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),

                (
                    'vehicle_type',
                    models.CharField(
                        default='Tesla Model 3',
                        max_length=50
                    )
                ),

                (
                    'battery_capacity',
                    models.FloatField(
                        default=75.0
                    )
                ),

                (
                    'current_charge',
                    models.FloatField(
                        default=75.0
                    )
                ),

                (
                    'latitude',
                    models.FloatField(
                        default=0.0
                    )
                ),

                (
                    'longitude',
                    models.FloatField(
                        default=0.0
                    )
                ),

                (
                    'speed',
                    models.FloatField(
                        default=0.0
                    )
                ),

                (
                    'status',
                    models.CharField(
                        choices=[
                            (
                                'idle',
                                'Idle'
                            ),
                            (
                                'driving',
                                'Driving'
                            ),
                            (
                                'charging',
                                'Charging'
                            ),
                            (
                                'maintenance',
                                'Maintenance'
                            ),
                        ],
                        default='idle',
                        max_length=20
                    )
                ),

                (
                    'last_updated',
                    models.DateTimeField(
                        auto_now=True
                    )
                ),

                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True
                    )
                ),

                (
                    'driver',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL
                    )
                ),
            ],

            options={
                'ordering': ['-last_updated'],
            },
        ),


        # ====================================================
        # 4. CHARGING LOG
        # ====================================================

        migrations.CreateModel(
            name='ChargingLog',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),

                (
                    'start_time',
                    models.DateTimeField()
                ),

                (
                    'end_time',
                    models.DateTimeField(
                        blank=True,
                        null=True
                    )
                ),

                (
                    'charge_amount',
                    models.FloatField()
                ),

                (
                    'duration',
                    models.IntegerField(
                        blank=True,
                        null=True
                    )
                ),

                (
                    'cost',
                    models.FloatField(
                        default=0.0
                    )
                ),

                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True
                    )
                ),

                (
                    'station',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='ev_tracking.chargingstation'
                    )
                ),

                (
                    'vehicle',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='ev_tracking.evvehicle'
                    )
                ),
            ],

            options={
                'ordering': ['-start_time'],
            },
        ),


        # ====================================================
        # 5. ALERT
        # ====================================================

        migrations.CreateModel(
            name='Alert',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),

                (
                    'alert_type',
                    models.CharField(
                        choices=[
                            (
                                'low_battery',
                                'Low Battery'
                            ),
                            (
                                'overheating',
                                'Overheating'
                            ),
                            (
                                'maintenance',
                                'Maintenance Required'
                            ),
                            (
                                'charging_available',
                                'Charging Available'
                            ),
                            (
                                'route_suggestion',
                                'Route Suggestion'
                            ),
                            (
                                'emergency',
                                'Emergency'
                            ),
                        ],
                        max_length=30
                    )
                ),

                (
                    'message',
                    models.TextField()
                ),

                (
                    'severity',
                    models.CharField(
                        choices=[
                            (
                                'low',
                                'Low'
                            ),
                            (
                                'medium',
                                'Medium'
                            ),
                            (
                                'high',
                                'High'
                            ),
                        ],
                        default='medium',
                        max_length=10
                    )
                ),

                (
                    'resolved',
                    models.BooleanField(
                        default=False
                    )
                ),

                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True
                    )
                ),

                (
                    'resolved_at',
                    models.DateTimeField(
                        blank=True,
                        null=True
                    )
                ),

                (
                    'vehicle',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='ev_tracking.evvehicle'
                    )
                ),
            ],

            options={
                'ordering': ['-created_at'],
            },
        ),


        # ====================================================
        # 6. TRAFFIC SNAPSHOT
        # ====================================================

        migrations.CreateModel(
            name='TrafficSnapshot',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),

                (
                    'expressway_section',
                    models.CharField(
                        max_length=100
                    )
                ),

                (
                    'timestamp',
                    models.DateTimeField()
                ),

                (
                    'vehicle_count',
                    models.IntegerField()
                ),

                (
                    'average_speed',
                    models.FloatField()
                ),

                (
                    'congestion_level',
                    models.CharField(
                        choices=[
                            (
                                'clear',
                                'Clear'
                            ),
                            (
                                'moderate',
                                'Moderate'
                            ),
                            (
                                'heavy',
                                'Heavy'
                            ),
                        ],
                        default='clear',
                        max_length=10
                    )
                ),

                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True
                    )
                ),
            ],

            options={
                'ordering': ['-timestamp'],

                'indexes': [
                    models.Index(
                        fields=[
                            'expressway_section',
                            '-timestamp'
                        ],
                        name='ev_tracking_express_c40e85_idx'
                    )
                ],
            },
        ),


        # ====================================================
        # 7. TRIP
        # ====================================================

        migrations.CreateModel(
            name='Trip',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),

                (
                    'start_time',
                    models.DateTimeField()
                ),

                (
                    'end_time',
                    models.DateTimeField(
                        blank=True,
                        null=True
                    )
                ),

                (
                    'energy_used',
                    models.FloatField(
                        default=0.0
                    )
                ),

                (
                    'distance_traveled',
                    models.FloatField(
                        default=0.0
                    )
                ),

                (
                    'charging_stops',
                    models.IntegerField(
                        default=0
                    )
                ),

                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True
                    )
                ),

                (
                    'route',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='ev_tracking.route'
                    )
                ),

                (
                    'vehicle',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='ev_tracking.evvehicle'
                    )
                ),
            ],

            options={
                'ordering': ['-start_time'],
            },
        ),
    ]